### ISSUE TITLE
provider "registry.terraform.io/-/heroku" produced an invalid new value for .local_checksum

### ISSUE THREAD

**Issue by douglashellowell** [terraform-providers/terraform-provider-heroku#269]
I am learning terraform and heroku deployment so I apologise if it my own mistake causing this.
The error (under Actual Behaviour) asks for issue to be reported.

# Terraform Version
Terraform v0.12.26

### Heroku Provider Version
+ provider.heroku v2.4.1

### Terraform Configuration Files
```hcl
variable "app_name" {
    description = "application name"
}
variable "HEROKU_EMAIL" {
    description = "email account tied to heroku profile"
}

variable "HEROKU_API_KEY" {
    description = "api key generated from `$ heroku authorizations:create`"
}
variable "HEROKU_API_ID" {
    description = "api ID generated from `$ heroku authorizations:create`"
}

# terraform {
#     backend "pg" {}
# }

provider "heroku" {
#  version = "~> 2.0"
 email = var.HEROKU_EMAIL
}

resource "heroku_app" "app" {
    name = var.app_name
    region = "eu"
}

resource "heroku_build" "nextjs" {
    app = heroku_app.app.id
    buildpacks = ["https://github.com/mars/heroku-nextjs"]

    source = {
        path = "../"
    }
}

resource "heroku_formation" "app" {
    app = heroku_app.app.id
    type= "web"
    quantity = 1
    size = "Free"
    depends_on = [heroku_build.nextjs]
}
```

### Actual Behavior
```
Error: Provider produced inconsistent final plan

When expanding the plan for heroku_build.nextjs to include new values learned
so far during apply, provider "registry.terraform.io/-/heroku" produced an
invalid new value for .local_checksum: was
cty.StringVal("SHA256:89a3f583662953676d3dfc3da0d61add50f6bb0eab2eeef85fa7f29dbcbce8db"),
but now
cty.StringVal("SHA256:68bde202faf37a4340bdc8a0f8bad0b03401f9b3c5b5a15760ec5dc36510f209").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -var-file variables.json -out hellowelldev.plan`
2. `terraform apply hellowelldev.plan`

**Comment by mars** [comment]
This kind of error happens when `heroku_build.source.path` is set to an ancestor path that contains the Terraform configuration being applied. In the issue's example configuration, `path = "../"`, the parent directory.

**Work-around**: Rearrange your project file structure so the Heroku build `path` is a child directory of the Terraform config.

This is not a bug we'll try to solve anytime soon, since there's a graceful workaround.

**Comment by douglashellowell** [comment]
Ah i see!

thank you so much for the explanation, i really appreciate it

**Comment by mars** [comment]
PR to document how to avoid this issue: #270

**Comment by hugbubby** [comment]
Honestly, I'm too lazy atm. I'm sorry. You should have enough to replicate the bug just with that info alone.

**Comment by davidji99** [comment]
Hi @hugbubby,

Whenever you get a chance. No rush =)

**Comment by mars** [comment]
I suspect this bug is related to the source path contents being changed during the lifecycle of the `terraform` command, resulting in unexpected changes to the source content hash.

If you’re using Terraform local state while including the Terraform working directory in the build source, then the `terraform.tfstate` files will be changing continuously.

As to why it fails on Terraform Cloud @hugbubby, maybe there’s something else happening to change the source contents during the apply?

**Comment by hugbubby** [comment]
@mars I have a temporary solution of begrudgingly using terraform cloud only for state management and putting the apply stage in a github action, but this has its own problems. New builds are getting pushed for every commit to the development branch, even if the source directories have no changes. Thankfully it doesn't break like terraform cloud, but maybe there should be a way to specify that only git-checked-files get involved in the builds so that these cloud platforms spooky filesystem changes don't get included?

**Comment by mars** [comment]
It sounds like there’s something about Terraform Cloud that does not agree with the filesystem-based source Heroku builds.

Definitely open to specific debugging feedback to solve this. I’m not personally a user of Terraform Cloud, yet.

**Comment by viktorianer** [comment]
> This kind of error happens when `heroku_build.source.path` is set to an ancestor path that contains the Terraform configuration being applied. In the issue's example configuration, `path = "../"`, the parent directory.
> 
> **Work-around**: Rearrange your project file structure so the Heroku build `path` is a child directory of the Terraform config.
> 
> This is not a bug we'll try to solve anytime soon, since there's a graceful workaround.

I do not understand, how to do this on my Rails app.

Rails project file structure looks like:

```bash
├── app
    ├── ...
...
├── db
   ├── migrate
    ...
...
├── terraform
   └── heroku
     ...
...
├── Gemfile
├── Gemfile.lock
├── Procfile
...
```

So, there is no chance to rearrange the Heroku build `path` to be a child directory of the Terraform config?!

Or I don't understand something?

**Comment by mars** [comment]
@viktorianer the Terraform configuration must be at the root, with app sources in subdirectories. So, in your case, re-arrange the repo to something like:

```
├── *.tf (terraform configurations)
├── rails_app
        ├── app
            ├── ...
        ...
        ├── db
           ├── migrate
            ...
        ...
        ├── Gemfile
        ├── Gemfile.lock
        ├── Procfile
        ...
```

…and the `heroku_build.source.path` would become `rails_app/`, a sub-directory of the Terraform configuration.

**Comment by viktorianer** [comment]
So, it means terraform is not a part of my app code (`rails_app` is under git version control)?
In Terraform, I have to put my "infrastructure as a code" outside the application, correct? 

Why? In Docker, Docker Compose, Kubernetes, Capistrano, Ansible, etc...it can be always part of your project. Which also makes sense to me.

**Comment by mars** [comment]
It's all in the repo, all under git version control, just a different hierarchy than what you assumed.

**Conceptual reasoning**: the infrastructure-as-code is the root. All of the things it creates/deploys are in sub-directories.

**Technical reasoning**: during `terraform` execution, it writes to the filesystem in its directory. Therefore, if the Terraform configuration directory is contained within source code that `heroku_build` references, then that directory of source will continuously be marked as having changes. You'll never get a clean apply.

**Comment by KyleMoran138** [comment]
Not super related, but I was also getting this issue when copying package.lock files with the "local_file" provider. Just in case anyone runs into this in the future
