### ISSUE TITLE
heroku_config resource

### ISSUE THREAD

**Issue by sheax0r** [terraform-providers/terraform-provider-heroku#47]
Currently, the only way to manage config variables on a heroku app is via the `heroku_app` resource. ie:

```hcl
resource "heroku_app" "my_app" {
  name = "my-app"
  config_vars {
    CONFIG_VAR = "value"
  }
}
```

This approach has a few problems:

1. It results in centralization of config vars. All config vars coming in from any other generated resources get set *in one place*. This means that the setting of a config var on an app can be far away from the place the var is defined, which may make it harder to follow the flow.

2. It makes it impossible to set config vars on an app that isn't managed by terraform. This is somewhat dangerous, since it means that even if all you really want to do is set a few config vars on an app, you're obligated to give your script the ability to manage other properties of the app as well (and even to destroy or create it).

## Possible Solution: heroku_config resource

We add a `heroku_config` resource, like this:

```hcl
resource "heroku_config" "my_config_vars" {
  app = "my-app"
  config_vars {
    CONFIG_VAR = "value"
  }
}
```

You can create multiple resources to configure different sets of config vars on the same app. It also still supports management of many config vars in the same resource, which is good for keeping things minimally verbose (my initial idea was to have one resource per config var, but I feel like this is a bit better).

### Config var conflicts
What to do if config vars conflict across multiple resources? I suggest we detect this situation and fail if it happens.

### Release Explosion
What to do about possibly generating lots of releases and restarting apps repeatedly?
I suggest we defer the actual setting of config vars until the end of a run. Is this possible? If it's not possible, I suggest that we just document it - I don't think this is necessarily a blocker.

**Comment by sheax0r** [comment]
@bernerdschaefer

**Comment by joestump** [comment]
Regarding the first problem, you can always pass `config_vars = "${var.config_vars}"` rather than creating a block like that. We do this in our Heroku app TF module. 

I'd also like to raise the idea of setting a single variable with a single resource, which would allow us to us things like `count` for variable setting:

```hcl
resource "heroku_app_config_var" "GITHUB_TOKEN" {
  app = "${heroku_app.foo.name}"
  name = "GITHUB_TOKEN"
  value = "${var.GITHUB_TOKEN}"
}
```

**Comment by bernerdschaefer** [comment]
The standalone config_var resource is an interesting one. For the default case, I think the current `config_vars` approach is the right one, but there are some cases where it breaks down.

For example, we have some apps which are paired together, where each needs the `web_url` of the other passed in as a config var. This seems to be impossible to model under the current method, because it introduces a circular dependency between the two app resources. We fall back to setting this config out of band, with post-processing scripts or a `null_resource` that uses `local_exec` to run `heroku config:set` commands.

I wonder how confusing as a user it would be to support both? Or how challenging it would be to correctly support both considering edge cases ("What if the same var is set both ways?")?

**Comment by sheax0r** [comment]
@bernerdschaefer regarding two apps each needing the web url of the other:

I think this is a problem endemic to all terraform resources that depend on each other. I believe that the right thing to do is to use predefined properties, rather than computed properties of newly created resources. 

ie, if you define your app's name rather than generating one, you will already know the "web_url" property, and you can define a property that would come out to be the same thing. Or if you use a domain name generated or defined separately, you also won't need the computed property.

@joestump I think the single-var standalone config var is a degraded case of the multi-variable approach? I have no objections to supporting both though, it might be nice to have a simpler syntax when you only want to handle one config var at a time. Please correct me if I'm wrong, and there is something materially different about the single-variable case.

**Comment by shirdoo** [comment]
I'm a fan of having `config_vars` exist as a separate resource, but it'll only be useful if its refreshed out of band with changes to the resource itself. I almost want to say we shouldn't be maintaining any remote state on our backend for the key/value map, but always pass through reads directly to the heroku platform API. For example, imagine a scenario I'm trying to solve in #102: 

```
resource "heroku_app" "app1" {
  name = "app1"
} 

resource "heroku_addon" "newrelic" {
  app = "app1"
}

resource "heroku_app" "app2" {
  name = "app2"
  config_vars = {
    "NEW_RELIC_LICENSE_KEY" = "${heroku_app.config_vars["NEW_RELIC_LICENSE_KEY"]}"
  }
}
```

heroku_app.app1.config_vars["NEW_RELIC_LICENSE_KEY"] throws, because the config_vars attribute on app1 was last refreshed when app1 was provisioned, so app1.config_vars knows nothing about any config_vars heroku_addon.newrelic added to app1. Considering the proposal in this issue, we'd have the same issue of the `heroku_app_config_var` resource getting refreshed out of band, in theory, at any time. For example, newrelic can decide to rotate their license key on their own cadence, which breaks our existing `config_vars` attribute on `heroku_app` resources. The current workaround I'm doing is two subsequent `terraform apply` commands. The first craps out on referencing a config_var key that the remote state doesn't know about, the second goes through because an apply refreshes all remote states before running the apply.

**Comment by bernerdschaefer** [comment]
@shirdoo As mentioned in #102, I think the way you'd solve the out-of-band dependent config var updates is to use a config var data source (which is a resource with no state) which depends on the addon resource (so it refreshes _after_ the addon is created).

**Comment by shirdoo** [comment]
sweet, a resource with no state is exactly what I'm looking for, I think this approach looks great

**Comment by shirdoo** [comment]
@bernerdschaefer  @sheax0r  can you check out #109 ? It's my stab at addressing this issue

**Comment by davidji99** [comment]
I think there's still some value to a separate config var resource as mentioned in the OP's first post even if it suffers from out-of-band changes.

**Comment by davidji99** [comment]
Closing this since https://github.com/terraform-providers/terraform-provider-heroku/pull/183 is merged.
